name: Build

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake (32-bit)
      run: |
        cmake -B build -G "Visual Studio 17 2022" -A Win32

    - name: Build
      run: |
        cmake --build build --config Release		
